
import { StatusType } from "../types/ip";

export const STATUS_LABELS: Record<StatusType, string> = {
  draft_classification: 'Draft Classification',
  draft_idf: 'Draft IDF',
  submitted_to_ttbdo: 'Submitted to TTBDO',
  under_ttbdo_review: 'Under TTBDO Review',
  prior_art_search: 'Prior Art Search',
  draft_application: 'Draft Application',
  filed_with_ipophil: 'Filed with IPOPHIL',
  wait_notice_publication: 'Waiting for Notice of Publication',
  wait_substantive_exam_report: 'Waiting for Substantive Exam Report',
  resolve_ser_defects: 'Resolve SER Defects',
  downgraded_to_um: 'Downgraded to UM',
  wait_notice_of_issuance: 'Waiting for Notice of Issuance',
  req_cert_of_registration: 'Request Certificate of Registration',
  wait_cert_of_registration: 'Waiting for Certificate of Registration',
  registered: 'Registered',
  published: 'Published',
  wait_formality_exam_report: 'Waiting for Formality Exam Report',
  resolve_fer_defects: 'Resolve FER Defects',
  request_revival: 'Request Revival',
  '2nd_publication': '2nd Publication',
  prepare_nice_classification: 'Prepare Nice Classification',
  approve_nice_classification: 'Approve Nice Classification',
  wait_registrability_report: 'Waiting for Registrability Report',
  resolve_rr_defects: 'Resolve RR Defects',
  techgen_sign: 'TechGen Sign',
  chancellor_sign: 'Chancellor Sign',
  notarization: 'Notarization',
  wait_notice_of_action: 'Waiting for Notice of Action',
  discussing_downgrade: 'Discussing Downgrade',
  resolve_additional_requirements: 'Resolve Additional Requirements',
  wait_statement_of_acc: 'Waiting for Statement of Account',
  pay_fee_application: 'Pay Application Fee',
  mailed_to_ipophl: 'Mailed to IPOPHL',
  closed: 'Closed',
};
