services:
  iris-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: iris-web:latest
    container_name: iris-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
