import { ApplicationType, InventorType, AttachmentType } from "../types/application";
import { IprStatus } from "../types/status";

export const dummyApplication: ApplicationType = {
  applicationId: 'demo-123',
  ipTitle: 'Low-Power Environmental Sensor Network',
  projectTitle: 'Smart Monitoring for Upland Farms',
  ipType: 'patent',
  currentStatus: 'filed_with_ipophil',
  applicationNumber: '100F',
  filingDate: '2025-11-25',
  lastUpdated: '2025-11-26T00:40:00Z',
  current_stage_deadline: '2025-12-30',
};

export const dummyFiles: AttachmentType[] = [
  {
    applicationId: 'demo-123',
    fileId: 'f1',
    filename: 'SensorDesign_v1.pdf',
    description: 'Initial technical description shared with TTBDO',
    fileType: 'pdf',
    uploadedAt: '2025-11-25T09:30:00Z',
    owner_id: 'tech',
  },
  {
    applicationId: 'demo-123',
    fileId: 'f12',
    filename: 'SensorDesign_v2.pdf',
    description: 'Initial technical description shared with TTBDO',
    fileType: 'pdf',
    uploadedAt: '2025-11-25T09:30:00Z',
    owner_id: 'tech'
  },
  {
    applicationId: 'demo-123',
    fileId: 'f13',
    filename: 'SensorDesign_v3.pdf',
    description: 'Initial technical description shared with TTBDO',
    fileType: 'pdf',
    uploadedAt: '2025-11-25T09:30:00Z',
    owner_id: 'tech'
  },
  {
    applicationId: 'demo-123',
    fileId: 'f2',
    filename: 'BlockDiagram.png',
    description: 'System architecture diagram',
    fileType: 'image',
    uploadedAt: '2025-11-25T10:12:00Z',
    owner_id: 'tech'
  },
  {
    applicationId: 'demo-123',
    fileId: 'f3',
    filename: 'MeetingNotes_GoogleDoc',
    description: 'Link to collaborative Google Doc for Q&A',
    fileType: 'link',
    uploadedAt: '2025-11-26T14:05:00Z',
    owner_id: 'ttbdo'
  },
];

export const dummyInventors: InventorType[] = [
  {
    inventorId: 'i1',
    full_name: 'Juan Dela Cruz',
    email: 'juan.delacruz@up.edu.ph',
    college: "CAS-Bio",
    userId: '123',
    comments: null
  },
  {
    inventorId: 'i2',
    full_name: 'Maria Santos',
    email: 'maria.santos@up.edu.ph',
    college: "CFOS-IA",
    userId: '1234',
    comments: null

  },
  {
    inventorId: 'i3',
    full_name: 'Alex Reyes',
    email: 'alex.reyes@up.edu.ph',
    college: 'CFOS',
    userId: null,
    comments: "Correct the surname spelling."
  },
];

export const dummyIprStatuses: IprStatus[] = [
  {
    statusId: 's1',
    status_type: 'draft_idf',
    note: 'Started initial IDF draft.',
    deadline: null,
    created_at: '2025-11-20T08:30:00Z',
  },
  {
    statusId: 's2',
    status_type: 'submitted_to_ttbdo',
    note: 'Disclosure form submitted for TTBDO review.',
    deadline: null,
    created_at: '2025-11-21T09:15:00Z',
  },
  {
    statusId: 's3',
    status_type: 'under_ttbdo_review',
    note: 'TTBDO is reviewing the IDF. Please expect follow-up questions if clarification is needed.',
    deadline: null,
    created_at: '2025-11-22T10:00:00Z',
  },
  {
    statusId: 's4',
    status_type: 'prior_art_search',
    note: 'Prior art search initiated by TTBDO.',
    deadline: null,
    created_at: '2025-11-23T19:20:00Z',
  },
  {
    statusId: 's5',
    status_type: 'draft_application',
    note: 'TTBDO is drafting the IPOPHL application. Kindly review the shared Google Doc and leave comments by the deadline.',
    deadline: '2025-11-26',
    created_at: '2025-11-24T21:05:00Z',
  },
  {
    statusId: 's6',
    status_type: 'filed_with_ipophil',
    note: 'Application filed with IPOPHL. Please monitor your email for any requests relayed by TTBDO.',
    deadline: null,
    created_at: '2025-11-26T00:40:00Z',
  },
];

export const dummyApplications: ApplicationType[] = [
  {
    applicationId: 1,
    ipTitle: "Smart Irrigation Control System",
    projectTitle: "IoT-Based Precision Agriculture",
    ipType: "patent",
    filingDate: new Date("2023-04-15"),
    registrationDate: new Date("2024-01-10"),
    fundingAgency: "Department of Science and Technology",
    techGens: ["Juan Dela Cruz", "Maria Santos", "Jose Ramirez"],
    colleges: ["CAS"],
    currentStatus: "wait_registrability_report",
  },
  {
    applicationId: 2,
    ipTitle: "AI-Driven Crop Disease Detection",
    projectTitle: "Machine Vision for Farm Diagnostics",
    ipType: "utility_model",
    filingDate: new Date("2022-08-12"),
    registrationDate: new Date("2023-05-30"),
    fundingAgency: "USAID",
    techGens: ["Anna Lee", "Carlos Mendoza", "Patrick Reyes"],
    colleges: ["CM", "CAS"],
    currentStatus: "prepare_nice_classification",
  },
  {
    applicationId: 3,
    ipTitle: "Solar-Powered Water Desalination Unit",
    projectTitle: "Sustainable Water Systems",
    ipType: "industrial_design",
    filingDate: new Date("2021-11-05"),
    registrationDate: new Date("2022-09-18"),
    fundingAgency: "CHED",
    techGens: ["Lorenzo Cruz", "Michelle Tan"],
    colleges: ["CFOS"],
    currentStatus: "submitted_to_ttbdo",
  },
  {
    applicationId: 4,
    ipTitle: "Portable Environmental Monitoring Device",
    projectTitle: "Low-Cost Air Quality Assessment",
    ipType: "copyright",
    filingDate: new Date("2023-02-20"),
    registrationDate: new Date("2023-12-01"),
    fundingAgency: "DENR",
    techGens: ["Rafael Torres", "Bianca Garcia", "Henry Lopez"],
    colleges: ["SOTECH"],
    currentStatus: "registered",
  },
  {
    applicationId: 5,
    ipTitle: "Learning Analytics Dashboard",
    projectTitle: "Adaptive Education Technologies",
    ipType: "copyright",
    filingDate: new Date("2022-06-14"),
    registrationDate: new Date("2022-10-22"),
    fundingAgency: "ADB",
    techGens: ["Samantha Rivera", "Daniel Cruz"],
    colleges: ["CAS", "SOTECH"],
    currentStatus: "draft_classification",
  },
  {
    applicationId: 6,
    ipTitle: "Autonomous Greenhouse Climate Controller",
    projectTitle: "Smart Agriculture Environment Management",
    ipType: "trademark",
    filingDate: new Date("2024-02-01"),
    registrationDate: new Date("2025-03-15"),
    fundingAgency: "Department of Agriculture",
    techGens: ["Miguel Santos", "Elena Rivera", "David Lopez"],
    colleges: ["CAS", "CFOS"],
    currentStatus: "draft_classification",
  },
  {
    applicationId: 7,
    ipTitle: "Drone-Assisted Pest Surveillance System",
    projectTitle: "AI-Enabled Crop Monitoring",
    ipType: "utility_model",
    filingDate: new Date("2023-07-18"),
    registrationDate: new Date("2024-02-20"),
    fundingAgency: "DA-PhilFUND",
    techGens: ["Isabel Cruz", "Ramon Morales", "Jessica Tan"],
    colleges: ["CM", "SOTECH"],
    currentStatus: "under_ttbdo_review",
  },
  {
    applicationId: 8,
    ipTitle: "Wind-Powered Irrigation Pump",
    projectTitle: "Renewable Energy for Agriculture",
    ipType: "industrial_design",
    filingDate: new Date("2022-03-12"),
    registrationDate: new Date("2023-01-25"),
    fundingAgency: "DOE",
    techGens: ["Paolo Garcia", "Anna Mendoza"],
    colleges: ["CFOS", "CAS"],
    currentStatus: "draft_application",
  },
  {
    applicationId: 9,
    ipTitle: "Wearable Soil Nutrient Sensor",
    projectTitle: "Precision Soil Analytics",
    ipType: "utility_model",
    filingDate: new Date("2023-05-10"),
    registrationDate: new Date("2024-04-08"),
    fundingAgency: "DA-RD",
    techGens: ["Lucia Torres", "Martin Reyes", "Clara Fernandez"],
    colleges: ["SOTECH", "CAS"],
    currentStatus: "draft_classification",
  },
  {
    applicationId: 10,
    ipTitle: "AI-Based Student Performance Predictor",
    projectTitle: "Next-Gen Learning Analytics",
    ipType: "utility_model",
    filingDate: new Date("2023-01-20"),
    registrationDate: new Date("2023-09-30"),
    fundingAgency: "CHED",
    techGens: ["Emilia Cruz", "Victor Tan"],
    colleges: ["CAS", "SOTECH"],
    currentStatus: "downgraded_to_um",
  },
];