@startuml
left to right direction
skinparam shadowing false
skinparam linetype ortho
skinparam ArrowColor #333
skinparam ArrowThickness 1
skinparam NoteBorderColor white
skinparam NoteBackgroundColor white

actor "TTBDO Administrator" as ADMIN

usecase "Authentication /\nLogin" as A_Login
usecase "Full IP Portfolio\nOverview" as A_Portfolio
usecase "User / Roles /\nPermissions Management" as A_URP
usecase "IP Application Status\nConfiguration" as A_StatusCfg
usecase "View IP Portfolio\nAnalysis/Summary" as A_Stats
usecase "Gather report of IP portfolio" as A_Report
usecase "View Audit Logs" as A_Logs
usecase "Generate API keys" as A_API

' Connections
ADMIN --> A_Login
ADMIN --> A_Portfolio
ADMIN --> A_URP
ADMIN --> A_StatusCfg
ADMIN --> A_Stats
ADMIN --> A_Report
ADMIN --> A_Logs
ADMIN --> A_API

@enduml